
import DashboardLayout from "@/components/dashBoard/DashboardLayout";
import MainDashboard from "@/components/dashBoard/MainDashboard";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard || MediMart",
  description: "Generated by create next app",
};
const DashboardLayoutNew = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <MainDashboard>{children}</MainDashboard>
    </div>
  );
};

export default DashboardLayoutNew;
