
import Sidebar from "@/components/dashBoard/SideBar";

import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "ShareNest App || dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="relative min-h-screen md:flex">
      <Sidebar/>

      <div className="flex-1 md:ml-64">
        <div className="p-5">
         {children}
        </div>
      </div>
    </div>
  );
};

export default DashboardLayout;
